# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 45de48652e943f6bb517cf072ad4ced4ad878d13b0dda6a54ec802db7fcdb0ec6570a186f2ca20c52589f883f73ec13b87320139ff8417fbd510b7e27dc9bd2b

test:
  secret_key_base: 9e2f1b37ecc5aa0534055edf64493b9a7add4ffa0963397d3ad4d23a35927bb3652f4bf9c41227081514c1be12ae942c7fce1b5a4a0705abf3f01d893e0b0641

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
